# Generated by Django 6.0.3 on 2026-03-25 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Catedratico', '0001_initial'),
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(help_text='Año académico (ej: 2024)', verbose_name='Año')),
                ('semestre', models.IntegerField(choices=[(1, 'Primer Semestre'), (2, 'Segundo Semestre')], help_text='1 = Primer Semestre, 2 = Segundo Semestre', verbose_name='Semestre')),
                ('seccion', models.CharField(help_text='Letra de la sección (A, B, C, etc.)', max_length=1, verbose_name='Sección')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de asignación')),
                ('catedratico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='Catedratico.catedratico', verbose_name='Catedrático')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='Curso.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Asignación de Curso',
                'verbose_name_plural': 'Asignaciones de Cursos',
                'db_table': 'asignacion_curso',
                'ordering': ['-anio', '-semestre', 'curso__nombre'],
                'unique_together': {('curso', 'anio', 'semestre', 'seccion')},
            },
        ),
    ]
