# Generated by Django 6.0.3 on 2026-03-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0003_curso'),
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota1', models.FloatField(blank=True, help_text='Primera evaluación (0-100)', null=True, verbose_name='Nota 1')),
                ('nota2', models.FloatField(blank=True, help_text='Segunda evaluación (0-100)', null=True, verbose_name='Nota 2')),
                ('nota3', models.FloatField(blank=True, help_text='Tercera evaluación (0-100)', null=True, verbose_name='Nota 3')),
                ('zona', models.FloatField(blank=True, help_text='Promedio de notas (calculado automáticamente)', null=True, verbose_name='Zona')),
                ('examen_final', models.FloatField(blank=True, help_text='Nota del examen final (0-100)', null=True, verbose_name='Examen Final')),
                ('nota_final', models.FloatField(blank=True, help_text='Nota final del curso (calculada automáticamente)', null=True, verbose_name='Nota Final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='Alumno.alumno', verbose_name='Alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='Curso.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'nota',
                'ordering': ['-created_at'],
                'unique_together': {('alumno', 'curso')},
            },
        ),
    ]
