# Generated by Django 6.0.3 on 2026-03-25 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nota', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['-created_at'], 'verbose_name': 'Calificación', 'verbose_name_plural': 'Calificaciones'},
        ),
    ]
