# Generated by Django 6.0.3 on 2026-03-25 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumno', '0003_curso'),
        ('Curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(help_text='Año académico (ej: 2024)', verbose_name='Año')),
                ('semestre', models.IntegerField(help_text='1 = Primer Semestre, 2 = Segundo Semestre', verbose_name='Semestre')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('aprobado', 'Aprobado'), ('reprobado', 'Reprobado')], default='activo', max_length=20, verbose_name='Estado')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Alumno.alumno', verbose_name='Alumno')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Curso.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Inscripción de Alumno',
                'verbose_name_plural': 'Inscripciones de Alumnos',
                'db_table': 'inscripcion_alumno',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('alumno', 'curso', 'anio', 'semestre')},
            },
        ),
    ]
